/** Rutas relativas a public/models (se usan con asset()). null = aún no hay modelo: se dibuja el placeholder. */
export const ASSETS = {
  hermes: 'hermes.glb',
  apolo: 'apolo.glb',
  calipso: 'calipso.glb',
  odiseo: 'odiseo.glb',
  humano: 'humano.glb',
  maia: 'maia.glb',
  alma: null,
  zeus: 'zeus.glb',
  lira: 'lira.glb',
  tortuga: 'tortuga.glb',
  ganado: 'ganado.glb',
  herma: 'herma.glb',
  arbol: 'arbol.glb',
  cipres: 'cipres.glb',
  olimpo_marco: 'olimpo_puertas_marco.glb',
  olimpo_hoja: 'olimpo_hoja.glb',
  olimpo_columna: 'olimpo_columna.glb',
  olimpo_templo: 'olimpo_templo.glb',
  caduceo: null,
  cuna: 'cuna.glb',
  telar: 'telar.glb',
  nube: 'nube.glb',
  cueva: 'cueva.glb',
  carta: 'carta.glb',
  moly: 'moly.glb',
} as const satisfies Record<string, string | null>
